spring.application.name=kanbanTaskManager

#spring.datasource.url= jdbc:postgresql://localhost:5432/task_manager
#spring.datasource.username=postgres
#spring.datasource.password=root

# Dynamic port assigned by cloud provider (defaults to 8080 locally)
server.port=${PORT:8080}

# Database Connection (pulls environment variables, falls back to localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
jwt.secret= "1N8JW4yehXG6QnjQ9GX97X7TywK8jH1Dre/oiprSKgNGvg9eio0Z4krfFXGZTIxb";
jwt.expiration = 864000000