# Dynamic port assigned by Render ($PORT)
server.port=${PORT}

# Render Database Connection (Strict Environment Variables)
# Expose actuator health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA & Hibernate Settings (Prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Swagger UI configuration for production
springdoc.swagger-ui.enabled=true