# Local Server Port
server.port=8080

# Local PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=root

# JPA & Hibernate Settings (Dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Swagger UI for local API testing
springdoc.swagger-ui.enabled=true