spring.application.name=kanbanTaskManager

spring.datasource.url= jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
jwt.secret= "1N8JW4yehXG6QnjQ9GX97X7TywK8jH1Dre/oiprSKgNGvg9eio0Z4krfFXGZTIxb";
jwt.expiration = 864000000