spring.application.name=kanbanTaskManager

spring.datasource.url= jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop